routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('companies.index');
});

Route::resource('companies', 'CompaniesController');
Route::resource('employees', 'EmployeesController');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = ['name','street','postcode','city','country'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function employees()
    {
        return $this->hasMany(Employee::class);
    }
}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function company()
    {
        return $this->belongsTo(Company::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use Illuminate\Http\Request;
use App\Http\Requests\CompaniesRequest;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::all();
        return view('companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CompaniesRequest $request
     * @return void
     */
    public function store(CompaniesRequest $request)
    {
        $company = Company::create($request->all());
        $request->session()->flash('success', "Company {$company->name} created!");
        return redirect()->route('companies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company $company
     * @return void
     */
    public function show(Company $company)
    {
        return view('companies.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Company $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CompaniesRequest $request
     * @param  \App\Models\Company $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompaniesRequest $request, Company $company)
    {
        $company->update($request->all());
        $request->session()->flash('success', "Company {$company->name} updated!");
        return redirect()->route('companies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param  \App\Models\Company $company
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Request $request, Company $company)
    {
        $request->session()->flash('error', "Company {$company->name} deleted!");
        $company->delete();
        return redirect()->route('companies.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all();
        return view('employees.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        //
    }
}

resources/views/app.blade.php
@include('partials.header')
@include('partials.body')
@include('partials.footer')

resources/views/companies/create.blade.php
@extends('app')

@section('main')

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
        <h1 class="h2">Create Company</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a href="{{ route('companies.index') }}" class="btn btn-outline-secondary">
                    <span data-feather="arrow-left"></span> Back
                </a>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-md-6">
            {!! Form::open(['route' => 'companies.store']) !!}

            @include('companies.partials.form')

            <button class="btn btn-primary btn-lg" type="submit">
                <span data-feather="plus"></span> Create Company
            </button>

            {!! Form::close() !!}
        </div>

    </div>

@stop

resources/views/companies/edit.blade.php
@extends('app')

@section('main')

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
        <h1 class="h2">Edit Company</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a href="{{ route('companies.index') }}" class="btn btn-outline-secondary">
                    <span data-feather="arrow-left"></span> Back
                </a>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-md-6">
            {!! Form::model($company, ['route' => ['companies.update', $company->id], 'method' => 'PATCH']) !!}

            @include('companies.partials.form')

            <button class="btn btn-primary btn-lg" type="submit">
                <span data-feather="send"></span> Update Company
            </button>

            {!! Form::close() !!}
        </div>

    </div>

@stop

resources/views/companies/index.blade.php
@extends('app')

@section('main')

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
        <h1 class="h2">Companies</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a href="{{ route('companies.create') }}" class="btn btn-primary"><span data-feather="plus"></span> Create</a>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-vcenter table-hover table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Company</th>
                <th>Street</th>
                <th>Postcode</th>
                <th>City</th>
                <th>Country</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($companies as $company)
                <tr>
                    <td>{{ $company->id }}</td>
                    <td>{{ $company->name }}</td>
                    <td>{{ $company->street }}</td>
                    <td>{{ $company->postcode }}</td>
                    <td>{{ $company->city }}</td>
                    <td>{{ $company->country }}</td>
                    <td class="text-center">
                        <div class="btn-group btn-group-sm">
                            <a href="{{ route('companies.show', $company->id) }}" class="btn btn-primary"><span data-feather="eye"></span></a>
                            <a href="{{ route('companies.edit', $company->id) }}" class="btn btn-warning"><span data-feather="edit-2"></span></a>
                            <a data-method="DELETE" data-confirm="Are you sure?" href="{{ route('companies.destroy', $company->id) }}" class="btn btn-danger"><span data-feather="x"></span></a>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

@stop

resources/views/companies/partials/form.blade.php
<div class="mb-3">
    {!! Form::label('name','Company Name', ['class' => 'control-label']) !!}
    {!! Form::text('name', null, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : '') ]) !!}
    {!! $errors->first('name', '<span class="invalid-feedback">:message</span>') !!}
</div>

<div class="mb-3">
    {!! Form::label('street','Street', ['class' => 'control-label']) !!}
    {!! Form::text('street', null, ['class' => 'form-control' . ($errors->has('street') ? ' is-invalid' : '') ]) !!}
    {!! $errors->first('street', '<span class="invalid-feedback">:message</span>') !!}
</div>

<div class="mb-3">
    {!! Form::label('postcode','Postcode', ['class' => 'control-label']) !!}
    {!! Form::text('postcode', null, ['class' => 'form-control' . ($errors->has('postcode') ? ' is-invalid' : '') ]) !!}
    {!! $errors->first('postcode', '<span class="invalid-feedback">:message</span>') !!}
</div>

<div class="mb-3">
    {!! Form::label('city','City', ['class' => 'control-label']) !!}
    {!! Form::text('city', null, ['class' => 'form-control' . ($errors->has('city') ? ' is-invalid' : '') ]) !!}
    {!! $errors->first('city', '<span class="invalid-feedback">:message</span>') !!}
</div>

<div class="mb-3">
    {!! Form::label('country','Country', ['class' => 'control-label']) !!} <span class="text-muted">(2 Letter Country Code)</span>
    {!! Form::text('country', null, ['class' => 'form-control' . ($errors->has('country') ? ' is-invalid' : '') , 'maxlength' => 2]) !!}
    {!! $errors->first('country', '<span class="invalid-feedback">:message</span>') !!}
</div>

resources/views/companies/show.blade.php
@extends('app')

@section('main')

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
        <h1 class="h2">{{ $company->name }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a href="{{ route('companies.index') }}" class="btn btn-outline-secondary"><span data-feather="arrow-left"></span> Back</a>
                <a href="{{ route('companies.edit', $company) }}" class="btn btn-primary"><span data-feather="edit-2"></span> Edit</a>
            </div>
        </div>
    </div>

    <h3 class="mb-3">Address</h3>
    <p><strong>{{ $company->name }}</strong><br />{{ $company->street }}<br />{{ $company->postcode }}<br />{{ $company->city }}<br />{{ $company->country }}</p>

    <h3 class="mb-3">Employees</h3>
    @include('employees.partials.table', ['data' => $company->employees])

@stop

resources/views/employees/index.blade.php
@extends('app')

@section('main')

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
        <h1 class="h2">Employees</h1>
    </div>

    @include('employees.partials.table',['data' => $employees])

@stop

resources/views/employees/partials/table.blade.php
<div class="table-responsive">
    <table class="table table-bordered table-hover table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Company</th>
            <th>E-mail</th>
        </tr>
        </thead>
        <tbody>
        @foreach($data as $employee)
            <tr>
                <td>{{ $employee->id }}</td>
                <td>{{ $employee->firstname }}</td>
                <td>{{ $employee->lastname }}</td>
                <td>{{ $employee->company->name }}</td>
                <td>{{ $employee->email }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/partials/body.blade.php
<div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
            @include('partials.nav')
        </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

        @if (Session::has('success'))
            <div class="alert alert-success" role="alert">
                <span data-feather="check-circle"></span>
                {{ Session::get('success') }}
            </div>
        @endif

        @if (Session::has('error'))
            <div class="alert alert-danger" role="alert">
                <span data-feather="x-circle"></span>
                {{ Session::get('error') }}
            </div>
        @endif

        @yield('main')
    </main>
</div>

resources/views/partials/footer.blade.php
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<script src="/js/delete.js"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>

</body>
</html>

resources/views/partials/header.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>blndr</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/css/app.css">
</head>

<body>
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">blndr</a>
</nav>

<div class="container-fluid">

resources/views/partials/nav.blade.php
<ul class="nav flex-column">
    <li class="nav-item">
        <a class="nav-link" href="{{ route('companies.index') }}">
            <span data-feather="briefcase"></span>
            Companies
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('employees.index') }}">
            <span data-feather="users"></span>
            Employees
        </a>
    </li>
</ul>